---
title: "vaccine"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(zoo)
```

## R Markdown

## import data
```{r}
df <- read_csv("../data/vaccination_covid_19_Laos.csv")
```
## change date on df
```{r}
df$date <- strptime(df$date, "%d/%m/%Y")
```


## Generate data for data sequence
```{r}
dateGerneate <- seq(as.Date(df$date[1]), Sys.Date(), by="day")
newDate <- tibble(dateGerneate) #create dataframe
colnames(newDate)[1] <- "date" #rename col
```

## Combine newDate to main dataframe
```{r}
fullDateDf <- df %>%
  full_join(newDate, by="date")
```

## Rearrange date order
```{r}
fullDateDf <- fullDateDf %>%
  arrange(date)
```

## fill na on total vaccinated col
```{r}
fullDateDf <- fullDateDf %>%
  fill(total_vaccinated, .direction="down") %>%
  fill(people_vaccinated, .direction="down") %>%
  fill(people_fully_vaccinated, .direction="down") %>%
  replace_na(list(source_url = "NA"))

```
## Calculate moving average and mutate data to main dataframe
```{r}
fullDateDf <- mutate(fullDateDf, movingAverage = rollmean(fullDateDf$total_vaccinated, 7, fill = NA))
```

## Plot data
```{r}
ggplot(data = fullDateDf) +
  geom_col(mapping = aes(x = date, y = total_vaccinated)) +
  geom_line(mapping= aes(x = date, y = movingAverage, color="red"))
```

## Create new dataframe for diff data
```{r}
diffData <- tibble(total_vaccinated = diff(fullDateDf$total_vaccinated),
                   people_vaccinated = diff(fullDateDf$people_vaccinated),
                   people_fully_vaccinated = diff(fullDateDf$people_fully_vaccinated))
```



## Calculate marginal
```{r}
diffData <- mutate(diffData, maTotal = rollmean(diffData$total_vaccinated, 7, fill = NA))
diffData <- mutate(diffData, maPeople_vaccinated = rollmean(diffData$people_vaccinated, 7, fill = NA))
diffData <- mutate(diffData, maPeople_fully_vaccinated = rollmean(diffData$people_fully_vaccinated, 7, fill = NA))
diffData <- mutate(diffData, date=fullDateDf$date[2:nrow(fullDateDf)])
```

## Plot Diff
```{r}
ggplot(data = diffData) +
  geom_col(mapping = aes(x = date, y = total_vaccinated, color="")) +
  geom_line(mapping= aes(x = date, y = maTotal, color="average (7 days)")) +
  scale_x_datetime(date_labels = "%d/%m", date_breaks = "3 weeks") +
  scale_color_brewer(palette = "Pastel1")

ggplot(data = diffData) +
  geom_line(mapping= aes(x = date, y = maPeople_vaccinated, color="vaccinated")) +
  geom_line(mapping= aes(x = date, y = maPeople_fully_vaccinated, color="fully vaccinated")) +
  scale_x_datetime(date_labels = "%d/%m", date_breaks = "3 weeks") +
  scale_color_brewer(palette = "Pastel1")
```

```{r}
# Export data
write.csv(fullDateDf, "../data/vaccination_covid_19_Laos_adjusted.csv")
write.csv(diffData, "../data/vaccination_covid_19_Laos_adjusted_diff.csv")
```

